# Generated by Django 4.1 on 2022-09-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('fathername', models.CharField(max_length=1000)),
                ('classname', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
