# Generated by Django 4.1 on 2022-09-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
    ]
